"""
Mapping data-version lockfile.

Every mapping file declares a `version` (a positive integer, bumped by one
on every content change - see docs/DATA_VERSIONING.md). The lockfile
`mappings/VERSIONS.lock` is the committed, human-auditable record of where
each mapping currently sits: id -> version -> path. A test asserts the
lockfile matches what is on disk, so a mapping cannot change version (or
appear/disappear) without the lock - and therefore the change - being
visible in review.

This is deliberately a *version* ledger, not a content hash: the project
identifies a dataset by the mapping version stamped on its samples, and
this file is the index of those versions. It stays pure stdlib and
dependency-free like the rest of bmwdiag.
"""

import json
import os
from typing import Any, Dict, List

from .loader import iter_mapping_files, load_file

__all__ = ["build_lock", "render_lock", "load_lock", "diff_lock", "LOCK_NAME"]

LOCK_NAME = "VERSIONS.lock"


def _rel(path: str) -> str:
    """Repo-relative, forward-slash path starting at `mappings/`."""
    p = path.replace(os.sep, "/")
    marker = "mappings/"
    i = p.rfind(marker)

    return p[i:] if i >= 0 else p


def build_lock(paths: List[str]) -> Dict[str, Any]:
    """
    Scan `paths` for mapping files and return the lock document: every
    mapping's id, version, production flag and repo-relative path, sorted
    by id for a stable diff.
    """
    entries: List[Dict[str, Any]] = []

    for root in paths:
        for found in iter_mapping_files(root):
            mapping = load_file(found)
            entries.append({
                "id": mapping.id,
                "version": mapping.version,
                "production": mapping.production,
                "path": _rel(mapping.source_path),
            })

    entries.sort(key=lambda e: e["id"])

    return {
        "note": (
            "Data-version ledger for the mapping files. Generated by "
            "`python3 -m bmwdiag.mapping lock mappings/`. Every mapping "
            "declares a positive integer version, bumped by one on every "
            "content change; this file records the current version of each "
            "and is checked by the test suite. See docs/DATA_VERSIONING.md."
        ),
        "mappings": entries,
    }


def render_lock(document: Dict[str, Any]) -> str:
    """Deterministic JSON text for the lockfile (trailing newline)."""
    return json.dumps(document, indent=2, sort_keys=False) + "\n"


def load_lock(path: str) -> Dict[str, Any]:
    """Read an existing lockfile."""
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def diff_lock(on_disk: Dict[str, Any], locked: Dict[str, Any]) -> List[str]:
    """
    Human-readable differences between the mappings on disk and the
    lockfile. Empty list means they agree. Compares the `mappings` lists
    only (the `note` is cosmetic).
    """
    def index(doc: Dict[str, Any]) -> Dict[str, Dict[str, Any]]:
        return {e["id"]: e for e in doc.get("mappings", [])}

    now, then = index(on_disk), index(locked)
    problems: List[str] = []

    for mid in sorted(set(now) - set(then)):
        problems.append(f"new mapping not in lock: {mid} (v{now[mid]['version']})")

    for mid in sorted(set(then) - set(now)):
        problems.append(f"mapping in lock but not on disk: {mid}")

    for mid in sorted(set(now) & set(then)):
        if now[mid]["version"] != then[mid]["version"]:
            problems.append(
                f"version mismatch for {mid}: disk v{now[mid]['version']} "
                f"vs lock v{then[mid]['version']} "
                "(bump intended? then regenerate the lock)"
            )

        if now[mid]["path"] != then[mid]["path"]:
            problems.append(
                f"path moved for {mid}: {then[mid]['path']} -> {now[mid]['path']}"
            )

    return problems
