"""
Data-driven report generation.

`n47-coverage.md` and the mechanical section of `n47-conflicts.md` are
generated from the normalized records so they can never drift from the
data. The narrative reports (source audit, legal notes, unresolved
questions) are hand-written and live directly under research/reports/.
"""

from typing import Any, Dict, List, Optional, Sequence, Set

from .conflicts import Conflict
from .model import ResearchRecord

__all__ = ["coverage_report", "conflicts_report", "withheld_sources"]

#: Coverage groups, in report order. A record joins the first group whose
#: predicate matches its normalized name or source naming.
GROUPS = (
    ("Basic engine", ("engine.rpm", "engine.load", "vehicle.speed")),
    ("DPF", ("dpf.",)),
    ("EGR", ("egr.",)),
    ("Drivetrain via DDE", ("transmission.",)),
    ("Regeneration history", ("regeneration",)),
    ("Temperatures", ("temperature",)),
    ("Turbo and air path", ("boost", "manifold", "maf", "air")),
    ("Fuel system", ("fuel.", "rail")),
    ("Injectors", ("injector",)),
    ("Electrical and IBS", ("voltage", "battery")),
)


def withheld_sources(sources: Optional[Dict[str, Dict[str, Any]]]) -> Set[str]:
    """
    Source ids whose manifest entry says `license.bulk_redistribution:
    withheld`.

    A withheld source still contributes every record to the (gitignored)
    normalized data; the *committed* coverage report lists only the rows
    somebody attached a normalized name to - a hand-picked fact with a
    stated meaning - and reports the rest as a count. That keeps the
    tracked tree free of a mechanical copy of the source table while the
    licence question in research/reports/legal-and-license-notes.md is
    open, and it is data in the manifest, not a threshold in code.
    """
    out: Set[str] = set()

    for source_id, entry in (sources or {}).items():
        license_block = entry.get("license") if isinstance(entry, dict) else None

        if isinstance(license_block, dict) and (
            license_block.get("bulk_redistribution") == "withheld"
        ):
            out.add(source_id)

    return out


def _group_for(record: ResearchRecord) -> str:
    name = record.normalized_signal or ""
    hay = " ".join([
        name,
        str(record.source.get("source_result_name", "")),
        str(record.source.get("source_record", "")),
    ]).lower()

    for title, needles in GROUPS:
        for needle in needles:
            if needle in name or (needle in hay and needle not in ("air",)):
                return title

    return "Other / unclassified"


def coverage_report(
    records: Sequence[ResearchRecord],
    gate_results: Dict[str, List[str]],
    sources: Optional[Dict[str, Dict[str, Any]]] = None,
) -> str:
    """
    The coverage table. `sources` is the manifest; rows from a source it
    marks `license.bulk_redistribution: withheld` are listed only when
    they carry a normalized name and counted otherwise (see
    `withheld_sources`). Without a manifest every row is listed.
    """
    withheld = withheld_sources(sources)
    signals = [r for r in records if r.record_type == "signal_definition"]
    grouped: Dict[str, List[ResearchRecord]] = {}
    held: Dict[str, Dict[str, int]] = {}

    for record in signals:
        group = _group_for(record)

        if record.source_id in withheld and not record.normalized_signal:
            counts = held.setdefault(group, {})
            counts[record.source_id] = counts.get(record.source_id, 0) + 1
        else:
            grouped.setdefault(group, []).append(record)

    lines = [
        "# N47 coverage",
        "",
        "Generated by `python3 -m research.build` from the normalized",
        "records - do not edit by hand. Every row keeps its original",
        "source naming; F10 applicability is `unverified` everywhere,",
        "because nothing has been validated on the target car yet.",
        "",
        f"Signal-definition records: **{len(signals)}**. Records passing",
        f"the executable-candidate gate: "
        f"**{sum(1 for k, v in gate_results.items() if not v)}**.",
        "",
    ]

    total_held = sum(sum(c.values()) for c in held.values())

    if total_held:
        names = ", ".join(f"`{s}`" for s in sorted(withheld))
        lines += [
            f"**{total_held}** rows from {names} are counted per group but",
            "not listed: the manifest marks that source",
            "`license.bulk_redistribution: withheld` (licence unresolved,",
            "see research/reports/legal-and-license-notes.md), so only the",
            "rows carrying a normalized name appear here. The full rows are",
            "in the gitignored normalized output that",
            "`python3 -m research.build` regenerates from the source cache.",
            "",
        ]

    order = [title for title, _ in GROUPS] + ["Other / unclassified"]

    for title in order:
        rows = grouped.get(title)
        counts = held.get(title)

        if not rows and not counts:
            continue

        lines += [f"## {title}", ""]

        if counts:
            for source_id, n in sorted(counts.items()):
                lines.append(
                    f"{n} unlisted `{source_id}` rows without a normalized name."
                )

            lines.append("")

        if not rows:
            continue

        lines.append(
            "| normalized | source record | variant | id | request | "
            "tier | verification | gate |"
        )
        lines.append("|---|---|---|---|---|---|---|---|")

        for r in sorted(rows, key=lambda x: (x.normalized_signal or "~", x.record_id)):
            missing = gate_results.get(r.record_id)
            gate = "**eligible**" if missing == [] else (
                f"missing: {', '.join(missing[:4])}" + ("…" if len(missing) > 4 else "")
                if missing else "-"
            )
            lines.append(
                f"| {r.normalized_signal or '-'} "
                f"| `{r.source.get('source_record', r.source.get('source_result_name', '?'))}` "
                f"| {r.applicability.get('sgbd', '?')} "
                f"| {r.source.get('source_identifier', '-')} "
                f"| {r.request.get('completeness', '?')} "
                f"| {r.evidence_tier} "
                f"| {r.verification} "
                f"| {gate} |"
            )

        lines.append("")

    return "\n".join(lines) + "\n"


def conflicts_report(conflicts: Sequence[Conflict], narrative: str) -> str:
    lines = [
        "# N47 cross-source conflicts",
        "",
        "The narrative analysis is hand-written; the detection table is",
        "generated by `python3 -m research.build` and lists every",
        "mechanical disagreement the pipeline found. Nothing here is",
        "resolved silently - each conflict names a validation experiment.",
        "",
        narrative,
        "",
        "## Mechanically detected conflicts",
        "",
    ]

    if not conflicts:
        lines.append("(none detected)")
    else:
        lines.append("| kind | key | record A (variant) | record B (variant) | detail |")
        lines.append("|---|---|---|---|---|")

        for c in sorted(conflicts, key=lambda x: (x.kind, x.key, x.a.record_id)):
            d = c.as_dict()
            lines.append(
                f"| {d['kind']} | `{d['key']}` "
                f"| `{d['a']}` ({d['a_variant']}) "
                f"| `{d['b']}` ({d['b_variant']}) "
                f"| {d['detail']} |"
            )

    return "\n".join(lines) + "\n"
