#!/usr/bin/env python3
"""
Turn Terraform outputs into the Ansible inventory.

Runs `terraform output -json` in infra/terraform, reads the droplet IP,
login user, WireGuard port and admin public keys, and writes
infra/ansible/inventory/hosts.yml (gitignored). This is the seam between
stage 1 (Terraform) and stage 2 (Ansible): the IP is never typed by hand.

Stdlib only - it writes the small YAML document itself rather than pulling
in PyYAML, keeping the toolchain dependency-free like the rest of the repo.

Usage:
    python3 infra/scripts/gen_inventory.py
"""

import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
INFRA = os.path.dirname(HERE)
TF_DIR = os.path.join(INFRA, "terraform")
INVENTORY = os.path.join(INFRA, "ansible", "inventory", "hosts.yml")


def terraform_outputs() -> dict:
    """`terraform output -json` as a dict of {name: value}."""
    try:
        raw = subprocess.run(
            ["terraform", f"-chdir={TF_DIR}", "output", "-json"],
            check=True, capture_output=True, text=True,
        ).stdout
    except FileNotFoundError:
        sys.exit("error: terraform not found on PATH")
    except subprocess.CalledProcessError as exc:
        sys.exit(f"error: terraform output failed - has it been applied?\n{exc.stderr}")

    doc = json.loads(raw)
    if not doc:
        sys.exit("error: no terraform outputs yet - run `make apply` first")

    return {k: v.get("value") for k, v in doc.items()}


def render_inventory(out: dict) -> str:
    ip = out.get("droplet_ip")
    user = out.get("ssh_user") or "root"
    wg_port = out.get("wireguard_port") or 51820
    keys = out.get("ssh_public_keys") or []

    if not ip:
        sys.exit("error: terraform output has no droplet_ip")

    lines = [
        "# Generated by infra/scripts/gen_inventory.py from terraform output.",
        "# Gitignored - do not edit by hand; re-run `make inventory`.",
        "all:",
        "  hosts:",
        "    analytics:",
        f"      ansible_host: {ip}",
        f"      ansible_user: {user}",
        "  vars:",
        f"    wireguard_port: {int(wg_port)}",
        "    admin_ssh_public_keys:",
    ]
    lines += [f"      - {json.dumps(k)}" for k in keys] or ["      []"]

    return "\n".join(lines) + "\n"


def main() -> int:
    out = terraform_outputs()
    os.makedirs(os.path.dirname(INVENTORY), exist_ok=True)

    with open(INVENTORY, "w", encoding="utf-8") as fh:
        fh.write(render_inventory(out))

    print(f"wrote {os.path.relpath(INVENTORY, INFRA)} "
          f"(host {out.get('droplet_ip')})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
